---
kind: namespace
apiVersion: v1
metadata:
  name: syncthing
---
# Deployment of syncthing + tailscale sidecar container
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      serviceAccount: tailscale
      serviceAccountName: tailscale
      containers:
        - env:
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
          image: syncthing/syncthing
          name: syncthing
          resources: {}
          volumeMounts:
            - mountPath: /var/syncthing/data
              name: vol-data
            - mountPath: /var/syncthing/config
              name: vol-config
        - env:
            - name: TS_KUBE_SECRET
              value: tailscale-auth
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  key: TS_AUTHKEY
                  name: tailscale-auth
                  optional: false
            - name: TS_USERSPACE
              value: "false"
            - name: TS_HOSTNAME
              value: syncthing
            - name: TS_SERVE_CONFIG
              value: serve.json
            - name: TS_EXTRA_ARGS
              value: --advertise-tags=tag:container
          image: ghcr.io/tailscale/tailscale:latest
          name: tailscale-syncthing-sidecar
          resources: {}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - mountPath: /serve.json
              name: serve-config
              subPath: serve.json
      volumes:
        - name: vol-data
          persistentVolumeClaim:
            claimName: syncthing-data
        - name: vol-config
          persistentVolumeClaim:
            claimName: syncthing-config
        - name: serve-config
          configMap:
            defaultMode: 420
            name: tailscale-serve-config
---
# Volume used by syncthing to store configuration, mounted at /var/syncthing/config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
# Volume used by syncthing to store the synced data, mounted at /var/syncthing/data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
---
# ConfigMap used by the tailscale sidecar to automatically serve the WebUI (:8384) at the HTTPS port with TLS termination
apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: syncthing
data:
  serve.json: |
    {
        "TCP": {
            "443": {
                "HTTPS": true
            }
        },
        "Web": {
            "${TS_CERT_DOMAIN}:443": {
                "Handlers": {
                    "/": {
                        "Proxy": "http://127.0.0.1:8384"
                    }
                }
            }
        }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: tailscale-auth
  namespace: syncthing
stringData:
  TS_AUTHKEY: ${TAILSCALE_KEY}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tailscale

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tailscale
  namespace: syncthing
rules:
  - apiGroups: [""]
    resourceNames: ["tailscale-auth"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
  namespace: syncthing
subjects:
  - kind: ServiceAccount
    name: tailscale
roleRef:
  kind: Role
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
