---
kind: Namespace
apiVersion: v1
metadata:
  name: syncthing
---
# Deployment of syncthing + tailscale sidecar container
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: syncthing
  name: syncthing
  namespace: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      containers:
        - env:
            - name: UID
              value: "1000"
            - name: GID
              value: "1000"
          image: syncthing/syncthing
          name: syncthing
          resources: {}
          volumeMounts:
            - mountPath: /var/syncthing/data
              name: vol-data
            - mountPath: /var/syncthing/config
              name: vol-config
      volumes:
        - name: vol-data
          persistentVolumeClaim:
            claimName: syncthing-data
        - name: vol-config
          persistentVolumeClaim:
            claimName: syncthing-config
---
# Volume used by syncthing to store configuration, mounted at /var/syncthing/config
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-config
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
# Volume used by syncthing to store the synced data, mounted at /var/syncthing/data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-data
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
---
# Service that exposes the syncthing UI over a tailscale service
apiVersion: v1
kind: Service
metadata:
  name: syncthing-webui
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - name: https
      port: 8384
      targetPort: 8384
---
# Service that exposes the syncthing ports for syncing to the outside world
apiVersion: v1
kind: Service
metadata:
  name: syncthing-sync
  namespace: syncthing
spec:
  selector:
    app: syncthing
  ports:
    - port: 22000
      targetPort: 22000
      name: sync-tcp
      protocol: TCP
    - port: 22000
      targetPort: 22000
      name: sync-udp
      protocol: UDP
    - port: 21027
      targetPort: 21027
      name: discovery
      protocol: UDP
  type: LoadBalancer
---
# Ingress for syncthing
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing
  namespace: syncthing
spec:
  defaultBackend:
    service:
      name: syncthing-webui
      port:
        number: 8384
  ingressClassName: tailscale
  tls:
    - hosts:
        - syncthing
